// Generates supabase/seed.sql from the bundled catalogue (lib/data/products.ts).
// Usage: npm run db:seed:generate
import { writeFileSync } from "node:fs";
import { products } from "../lib/data/products.ts";

const q = (value) => `'${String(value).replaceAll("'", "''")}'`;
const arr = (values) => `array[${values.map(q).join(", ")}]::text[]`;

const rows = products.map((p) =>
  `  (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.description)}, ${p.price}, ${q(p.imageUrl)}, ${arr(p.galleryUrls)}, ${q(p.category)}, ${p.stock}, ${p.badge ? q(p.badge) : "null"})`,
);

const sql = `-- Generated by scripts/generate-seed.mjs from lib/data/products.ts. Do not edit by hand.
-- Safe to re-run: existing products are updated by slug.
insert into public.products (id, name, slug, description, price, image_url, gallery_urls, category, stock, badge)
values
${rows.join(",\n")}
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  price = excluded.price,
  image_url = excluded.image_url,
  gallery_urls = excluded.gallery_urls,
  category = excluded.category,
  stock = excluded.stock,
  badge = excluded.badge;
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote supabase/seed.sql with ${products.length} products`);
